name: SPPU Result Watcher

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore result cache
        uses: actions/cache@v4
        with:
          path: known_results.json
          key: sppu-results-cache

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run watcher
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python -u sppu_result_watcher.py


      - name: Save result cache
        uses: actions/cache@v4
        with:
          path: known_results.json
          key: sppu-results-cache
